apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: bazel-img-build
spec:
  description: >-
    The pipeline to clone from a GitHub repo and build Docker container image
  params:
    - name: repo-url
      description: The private GitHub Repo
      default: https://github.tools.sap/phoenix/Phoenix
    - name: repo-revision
      description: The GitHub revision to use
      default: main
    - name: dockerfile
      description: Dockerfile name
      default: Dockerfile
    - name: image-url
      description: docker image URL in the container registry
  workspaces:
    - name: polygon
  tasks:
    - name: clone-repo
      taskRef:
        name: git-clone
      params:
        - name: url
          value: $(params.repo-url)
        - name: revision
          value: $(params.repo-revision)
        - name: deleteExisting
          value: 'true'
      workspaces:
        - name: output
          workspace: polygon
    - name: create-image
      taskRef:
        name: build-docker-image
      params:
        - name: dockerfile
          value: $(params.dockerfile)
        - name: image-url
          value: $(params.image-url)
      runAfter:
        - clone-repo
      workspaces:
      - name: source
        workspace: polygon
