apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: docker-build-push
  namespace: ds-tkn
spec:
  params:
  - name: IMAGE
    description: Name (reference) of the image to build.
  - name: DOCKERFILE
    description: Path to the Dockerfile to build.
    default: ./Dockerfile
  - name: BUILDER_IMAGE
    description: The image on which builds will run
    default: gcr.io/sap-sc-learn/ds-test/bazel:latest
  workspaces:
    - name: source

  steps:
  - name: build
    workingDir: $(workspaces.source.path)
    image: $(params.BUILDER_IMAGE)
    command:
    - docker
    - build
    - --tag=$(params.IMAGE)
    - --file=$(params.DOCKERFILE)
    securityContext:
      runAsUser: 0
